// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb84DfjVNpiQxfUdp7VKvbA20rbJGnV7Q',
    authDomain: 'stock-ease-3f322.firebaseapp.com',
    projectId: 'stock-ease-3f322',
    storageBucket: 'stock-ease-3f322.appspot.com',
    messagingSenderId: '342552572755',
    appId: '1:342552572755:web:e9e8d6810e431f7fc1a7a6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSI4w0Phc2Ab2OF1RPbksT0H6oJShZM1g',
    appId: '1:342552572755:android:e561a1cf44525691c1a7a6',
    messagingSenderId: '342552572755',
    projectId: 'stock-ease-3f322',
    storageBucket: 'stock-ease-3f322.firebasestorage.app',
  );
}
